# Merge Exclude directives from different config files
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-performance
  # Standard's config uses this custom cop, so it must be loaded
  - standard/cop/semantic_blocks

inherit_gem:
  # Integration with StandardRB based on:
  # https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard#one-standard-to-rule-them-all
  standard: config/base.yml

inherit_from:
  - .rubocop_todo.yml

# -------------------------
# StandardRB rule overrides
# -------------------------
Metrics:
  Enabled: true

Metrics/BlockLength:
  IgnoredMethods:
    - FactoryBot.define
    - describe
    - context

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HashAlignment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: compact

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false
