version: 2.1

commands:
  bundle_install:
    description: 'Perform bundler installation, relying on CircleCI cache for performance'
    steps:
      - restore_cache:
          keys:
            - bundler-cache-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: 'Bundle install'
          command: |
            set -euxo pipefail
            bundle config set frozen 'true'
            bundle install --path=.bundle
      - save_cache:
          key: bundler-cache-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle
  yarn_install:
    description: 'Perform node module installation, relying on CircleCI cache for performance'
    steps:
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: 'Yarn install'
          command: bin/yarn install
      - save_cache:
          key: node-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  webpacker_compile:
    steps:
      - run:
          name: 'Compile webpacker assets'
          command: |
            set -euxo pipefail
            bundle config path .bundle
            bundle exec rails webpacker:compile
  run_rubocop:
    description: 'Run rubocop'
    steps:
      - run:
          name: 'Run rubocop'
          command: |
            set -euxo pipefail
            bundle config path .bundle
            bundle exec rubocop
  rspec_backend:
    description: 'Run rspec backend specs'
    steps:
      - run:
          name: 'Run rspec backend specs'
          command: |
            set -euxo pipefail
            bundle config path .bundle
            bundle exec rails db:create
            bundle exec rspec --format progress --format RspecJunitFormatter -o /tmp/rspec_backend/rspec.xml
  mocha_specs:
    description: 'Run mocha specs'
    steps:
      - run:
          name: 'Run mocha specs'
          command: yarn test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: /tmp/frontend/test-results.xml
  rspec_system:
    description: 'Run rspec system specs'
    steps:
      - run:
          name: 'Run rspec system specs'
          command: |
            set -euxo pipefail
            bundle config path .bundle
            bundle exec rails db:create
            bundle exec rspec --format progress --format RspecJunitFormatter -o /tmp/rspec_system/rspec.xml spec/system

executors:
  app_only:
    docker:
      - image: circleci/ruby:2.7.2-node
  app_and_db:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          POSTGRES_HOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: mutualaid_test
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: circleci

jobs:
  bundle:
    executor: app_only
    steps:
      - checkout
      - bundle_install
      - persist_to_workspace:
          root: .
          paths: [.bundle]
  yarn:
    executor: app_only
    steps:
      - checkout
      - yarn_install
      - persist_to_workspace:
          root: .
          paths: [node_modules]
  webpacker:
    executor: app_only
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - attach_workspace: {at: .}
      - webpacker_compile
      - persist_to_workspace:
          root: .
          paths: [public/packs-test]
  rubocop:
    executor: app_only
    steps:
      - checkout
      - attach_workspace: {at: .}
      - run_rubocop
  backend_specs:
    executor: app_and_db
    steps:
      - checkout
      - attach_workspace: {at: .}
      - rspec_backend
      - store_test_results: {path: /tmp/rspec_backend}
  frontend_specs:
    executor: app_only
    steps:
      - checkout
      - attach_workspace: {at: .}
      - mocha_specs
      - store_test_results: {path: /tmp/frontend}
      - store_artifacts: {path: /tmp/frontend}
  system_specs:
    executor: app_and_db
    environment:
      HEADLESS_CHROME: true
    steps:
      - checkout
      - attach_workspace: {at: .}
      - rspec_system
      - store_test_results: {path: /tmp/rspec_system}

workflows:
  version: 2.1
  mutual_aid:
    jobs:
      - bundle
      - yarn
      - rubocop:
          requires:
            - bundle
      - backend_specs:
          requires:
            - bundle
            - yarn
      - frontend_specs:
          requires:
            - yarn
      - webpacker:
          requires:
            - bundle
            - yarn
      - system_specs:
          requires:
            - bundle
            - yarn
            - webpacker
